import { Poppins } from 'next/font/google';
import './globals.css';

const Poppings = Poppins({
  variable: '--font-poppin-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'], // array for multiple weights
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Poppings.variable} antialiased `}>{children}</body>
    </html>
  );
}
